name: fcnd
channels:
    - conda-forge
dependencies:
    - python==3.6.3
    - matplotlib==2.1.1
    - jupyter==1.0.0
    - future==0.16.0
    - pip:
        - git+https://github.com/udacity/udacidrone.git
        - visdom==0.1.7

